### PR TITLE
Updated system logos

### PR DESCRIPTION
**Pull request by nicjansma**
* Adds logos (via [ES-DE's rbsimple-DE theme](https://gitlab.com/es-de/emulationstation-de/-/tree/stable-1.2/themes/rbsimple-DE)) for several missing systems:
    * android
    * arduboy
    * atomiswave
    * channelf
    * gameandwatch
    * gx4000
    * megaduck
    * n64dd
    * nds
    * pcenginecd
    * pico8
    * satellaview
    * sg1000 (copy of sg-1000)
    * supervision
    * tic80
    * x1
    * x68000
* Where possible, replaced SVGs that were black-and-white only with color editions
* Where possible, used logos that were more horizontal than square or vertical, to fit with the theme
* Several of the systems SVGs had inline-CSS which isn't compatible with [SVG Tiny 1.2](https://github.com/mmatyas/pegasus-frontend/issues/870) that Pegasus uses.  As a result, those icons' colors would be all black (even if the SVG previewed with color in e.g. Chrome)
    * To fix this, I've copied a few additional logos from rbsimple-DE and ran them through Inkscape's _Optimize SVG_ save-as to remove the inline CSS and replace as proper SVG attributes.

### CODE REVIEW

**Comment by mmatyas** [comment]
Thank you, looks nice!

One thing though, you mentioned *"Where possible, used logos that were more horizontal than square or vertical"*, but looking at the files, it seems some of the logos are actually square, at least here on GitHub:

- logo/atomiswave.svg
- logo/gx4000.svg
- logo/megaduck.svg
- logo/n64dd.svg
- logo/satellaview.svg
- logo/supervision.svg
- logo/tic80.svg
- logo/x68000.svg

Could you double check if that's intentional?

**Comment by nicjansma** [comment]
Hm, for some of those logos (e.g. atomiswave, satellaview, supervision, tic80, x68000), I agree they have some "blank" vertical spacing (i.e. they're not trimmed to the top and bottom pixel of the logo -- those logos are centered vertically but there's transparent pixels above and below).

For what it's worth, when displayed in a Pegasus skin they look OK because the image bounding box shrinks to the max dimension, which in all of those cases is still horizontal.  So they shouldn't be "shrunk" vertically at all.

If you think they'd be better chopped at the top/bottom pixel, I could probably pretty easily trim them (I think most of those were copied direct from the [rbsimple-DE theme](https://gitlab.com/es-de/emulationstation-de/-/tree/stable-1.2/themes/rbsimple-DE))

gx4000, megaduck, n64dd seem fine, with some very minor vertical spacing if any:

image

**Comment by mmatyas** [comment]
I'm perfectly fine with some padding, but for me they appear like this:

Screenshot_2023-01-23_09-53-47
Screenshot_2023-01-23_09-54-06
Screenshot_2023-01-23_09-54-21

Which is why I'm not sure which one is intentional and which one isn't. On the other hand, after downloading some of them, they seem to work fine, so this might be some browser rendering issue... in which case, I wonder if there's still anything renderer-dependent in the files?

**Comment by mmatyas** [comment]
On another note, I've looked into some of the files, and found some interesting sections. `megaduck.svg`, for example still has CSS:

```
<style type="text/css">
	.st0{fill:#0D1415;}
	.st1{fill:#FFFFFF;}
	.st2{fill:#636363;}
	.st3{fill:#3CC7C7;}
</style>
<g fill="#415e81">
		<path class="st3" d="...
```

While `n64dd.svg` seems to have invisible text blocks:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 252.799 110.437">
<text transform="translate(93.823 98.972)" fill="#c23435" font-family="ArialMT" font-size="2">I don’t like bugs!</text>
```

If you say the MegaDuck logo works in Pegasus, I'm fine with that, but just in case could you double check it?

**Comment by nicjansma** [comment]
I think there's something funky with the Github UI that it's showing bonus transparent pixels -- I see something very different (with essentially no transparent padding).  When looking at these files in Inkscape for example, there's no padding:

image

Fixed the MegaDuck (and in supervision) logo to remove those `<style>`s.

Remove the hidden texts from x1, coco, n64dd, tic80

**Comment by mmatyas** [comment]
Sorry for the late reply! Thanks for the fix, the files look fine locally, so I think this can be merged.

**Pull request merged**
